=== 2fort-cremator/hud-db/utils/hud-data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HUD Data",
  "description": "Data about a HUD",
  "type": "object",
  "required": ["name", "author", "repo", "hash", "resources"],
  "properties": {
    "name": {
      "description": "Display name of your HUD",
      "type": "string"
    },
    "author": {
      "description": "Display name of you, the active developer of the HUD (however, outdated HUD maintenance may not count as authoring in some cases)",
      "type": "string"
    },
    "contributors": {
      "description": "Display names of anyone you would like to credit for the creation/development of the HUD. Not to be used for general credits, but major and direct contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "releaseDate": {
      "description": "Initial release date of the HUD",
      "type": "string"
    },
    "social": {
      "description": "Links to your social media profiles",
      "type": "object",
      "properties": {
        "support": {
          "description": "A link people can use to support you financially",
          "type": "string"
        },
        "issues": {
          "description": "An extra link where users can get help/report issues. If not present, will use GitHub Issues.",
          "type": "string"
        },
        "steam_profile": {
          "description": "Your SteamID64",
          "type": "string"
        },
        "steam_group": {
          "description": "Your Steam group",
          "type": "string"
        },
        "twitter": {
          "description": "Your Twitter handle",
          "type": "string"
        },
        "discord": {
          "description": "Your Discord invite code, not the full URL",
          "type": "string"
        },
        "album": {
          "description": "Link to some Imgur album or other to provide more images",
          "type": "string"
        }
      }
    },
    "flags": {
      "description": "A list of boolean flags whose presence indicates the existence of a feature of some kind",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "fonts",
          "menus",
          "scoreboards",
          "crosshairs",
          "minmode",
          "streamer-mode",
          "materials",
          "customization"
        ]
      },
      "uniqueItems": true
    },
    "traits": {
      "description": "Optional structured mapping of values",
      "type": "object",
      "properties": {
        "os": {
          "description": "What operating systems does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["windows", "mac", "linux"]
          },
          "uniqueItems": true
        },
        "gamemode": {
          "description": "What gamemodes does the HUD customize for",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "tournament",
              "comp",
              "arena",
              "ad",
              "ctf",
              "cp",
              "halloween",
              "koth",
              "mannpower",
              "mvm",
              "pass",
              "pl",
              "plr",
              "pd",
              "rd",
              "sd",
              "tc"
            ]
          },
          "uniqueItems": true
        },
        "res": {
          "description": "What aspect ratios does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "1/1",
              "4/3",
              "5/4",
              "16/10",
              "16/9",
              "17/9",
              "21/9",
              "32/9"
            ]
          },
          "uniqueItems": true
        },
        "position": {
          "description": "What position is the ammo/health in the HUD (multiple customization options can be available)",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["center", "corners", "default"]
          },
          "uniqueItems": true
        },
        "lang": {
          "description": "What languages does the HUD support (if it has custom language files)",
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      }
    },
    "tags": {
      "description": "A list of words associated with the HUD for discovery. Be general. First tag is considered primary and used as a category. There is no list of valid tags, but they are subject to review for usefulness/'spamminess'.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repo": {
      "description": "The URL to the repository where the HUD is hosted",
      "type": "string"
    },
    "hash": {
      "description": "The hash of the latest commit in the repository",
      "type": "string"
    },
    "prerelease": {
      "description": "Whether the HUD is a prerelease",
      "type": "boolean"
    },
    "verified": {
      "description": "Whether the HUD has been verified by a member of the  team",
      "type": "boolean"
    },
    "parent": {
      "description": "The name of the HUD this HUD is based on",
      "type": "string"
    },
    "resources": {
      "description": "A list of resources associated with the HUD",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 15,
      "uniqueItems": true
    }
  }
}

=== 2fort-cremator/hud-db/hud-data/mini-hud.json
{
  "name": "Mini Hud",
  "author": "Unknown",
  "contributors": [
    "techno"
  ],
  "social": {
    "album": "https://imgur.com/a/YqeYDu5"
  },
  "repo": "https://github.com/TechnoSL/Mini-Hud",
  "hash": "4c082b4bd4860a64303a07719e3260ee35def9cd",
  "parent": "",
  "resources": [
    "minihud-menu",
    "minihud-loadout",
    "minihud-gameplay"
  ]
}

=== 2fort-cremator/hud-db/hud-data/ciba-hud.json
{
  "name": "cibahud",
  "author": "CibaCity",
  "social": {
    "steam_group": "cibascity",
    "album": "https://imgur.com/a/OoX4yAz"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "materials"
  ],
  "traits": {
    "os": ["windows"],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": ["4/3", "5/4", "16/9", "16/10"]
  },
  "repo": "https://github.com/CibaCity/cibahud",
  "hash": "9738f77676bb1b486e64a4d256ffd22388ad7abb",
  "resources": ["ciba-hud-banner"]
}

=== 2fort-cremator/hud-db/hud-data/jofrehud.json
{
  "name": "JofreHUD",
  "author": "Jofre Problem?",
  "social": {
    "album": "https://imgur.com/a/8RKavUI"
  },
  "flags": [
    "fonts",
    "menus",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "arena",
      "ad",
      "ctf",
      "cp",
      "koth",
      "pl"
    ],
    "res": [
      "16/9",
      "16/10"
    ]
  },
  "repo": "https://github.com/Jofre-Problem/JofreHUD",
  "hash": "9b918c85735c6cea9f6ff67a598ee74207c7003c",
  "resources": [
    "jofrehud-banner"
  ]
}

=== 2fort-cremator/hud-db/hud-data/voidhud-classic.json
{
  "name": "voidHUD Classic",
  "author": "static",
  "social": {
    "steam_group": "voidhud",
    "discord": "https://discord.com/invite/NtQ3FsT",
    "album": "https://imgur.com/a/BKWgR"
  },
  "repo": "https://github.com/TheStaticVoid/VoidHUD2.0",
  "hash": "8165dbad858243a90ec7c8a35ea6bd701f5738e1",
  "parent": "void-hud-2.0",
  "resources": [
    "voidhud-classic-banner",
    "image00",
    "image01",
    "image02",
    "image03",
    "image04",
    "image05",
    "image06"
  ]
}

=== 2fort-cremator/hud-db/hud-data/broesel-crsp.json
{
  "name": "Broesel Crsp",
  "author": "Hypnotize, extracrispy",
  "social": {
    "album": "https://imgur.com/a/Ywblk"
  },
  "repo": "https://github.com/Hypnootize/Crsp-Broesel",
  "hash": "670670ccef8726aadfde8dc186da90bcf866dc87",
  "parent": "broesel-hud",
  "resources": [
    "broesel-crsp-banner"
  ]
}

=== 2fort-cremator/hud-db/hud-data/technohud.json
{
    "name": "technohud",
    "author": "techno",
    "releaseDate": "2024-01-11",
    "social": {
        "steam_profile": "76561198172101254",
        "discord": "rc4322",
        "album": "https://imgur.com/a/aHdoUKi"
    },
    "flags": ["fonts", "menus",  "materials", "customization"],
    "traits": {
        "os": ["windows"],
        "gamemode": ["tournament", "comp", "ad", "cp", "koth", "mannpower", "pl", "plr"],
        "res": ["4/3", "16/9"],
        "position": ["center"],
        "lang": ["en"]
    },
    "tags": ["light", "minimal", "monochrome"],
    "repo": "https://github.com/TechnoSL/technohud",
    "hash": "55f3cac33376c936c4db089382f15b2ecad4b467",
    "prerelease": true,
    "resources": [
        "th-banner",
        "th-menu",
        "th-loadout",
        "th-backpack",
        "th-gameplay"
    ]
}

=== 2fort-cremator/hud-db/hud-data/insomniahud.json
{
  "name": "InsomniaHUD",
  "author": "Lead",
  "social": {
    "album": "https://github.com/p3tr1ch0r/insomniaHUD#screenshots",
    "steam_profile": "https://steamcommunity.com/profiles/76561199066986123"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "ad",
      "ctf",
      "cp",
      "koth",
      "mannpower",
      "pl",
      "plr",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "16/9",
      "16/10",
      "21/9",
      "32/9"
    ],
    "position": [
      "center"
    ],
    "lang": [
      "en"
    ]
  },
  "tags": [
    "minimal",
    "monochrome",
    "customizable"
  ],
  "repo": "https://github.com/p3tr1ch0r/insomniaHUD",
  "hash": "f876f002e59df7a34b40f73e6b0d6ab4bd3aa4f9",
  "prerelease": true,
  "resources": [
    "insomniahud-banner",
    "main_menu",
    "main_menu_ingame",
    "customization_menu",
    "items_menu",
    "backpack",
    "class_loadout",
    "team_menu",
    "class_menu",
    "payload",
    "attack_defend",
    "control_points",
    "koth",
    "ctf"
  ]
}

=== 2fort-cremator/hud-db/hud-data/mk-hud.json
{
  "name": "mkhud",
  "author": "kmarcie",
  "social": {
    "steam_group": "mkhud",
    "album": "https://imgur.com/a/wHHbv"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ]
  },
  "repo": "https://github.com/kmarcie/mkHUD",
  "hash": "0e08677b70e77c4f4fc0265578401e61b1c6abed",
  "resources": [
    "mk-hud-banner"
  ]
}
