=== 2fort-cremator/hud-db/utils/hud-data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HUD Data",
  "description": "Data about a HUD",
  "type": "object",
  "required": ["name", "author", "repo", "hash", "resources"],
  "properties": {
    "name": {
      "description": "Display name of your HUD",
      "type": "string"
    },
    "author": {
      "description": "Display name of you, the active developer of the HUD (however, outdated HUD maintenance may not count as authoring in some cases)",
      "type": "string"
    },
    "contributors": {
      "description": "Display names of anyone you would like to credit for the creation/development of the HUD. Not to be used for general credits, but major and direct contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "releaseDate": {
      "description": "Initial release date of the HUD",
      "type": "string"
    },
    "social": {
      "description": "Links to your social media profiles",
      "type": "object",
      "properties": {
        "support": {
          "description": "A link people can use to support you financially",
          "type": "string"
        },
        "issues": {
          "description": "An extra link where users can get help/report issues. If not present, will use GitHub Issues.",
          "type": "string"
        },
        "steam_profile": {
          "description": "Your SteamID64",
          "type": "string"
        },
        "steam_group": {
          "description": "Your Steam group",
          "type": "string"
        },
        "twitter": {
          "description": "Your Twitter handle",
          "type": "string"
        },
        "discord": {
          "description": "Your Discord invite code, not the full URL",
          "type": "string"
        },
        "album": {
          "description": "Link to some Imgur album or other to provide more images",
          "type": "string"
        }
      }
    },
    "flags": {
      "description": "A list of boolean flags whose presence indicates the existence of a feature of some kind",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "fonts",
          "menus",
          "scoreboards",
          "crosshairs",
          "minmode",
          "streamer-mode",
          "materials",
          "customization"
        ]
      },
      "uniqueItems": true
    },
    "traits": {
      "description": "Optional structured mapping of values",
      "type": "object",
      "properties": {
        "os": {
          "description": "What operating systems does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["windows", "mac", "linux"]
          },
          "uniqueItems": true
        },
        "gamemode": {
          "description": "What gamemodes does the HUD customize for",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "tournament",
              "comp",
              "arena",
              "ad",
              "ctf",
              "cp",
              "halloween",
              "koth",
              "mannpower",
              "mvm",
              "pass",
              "pl",
              "plr",
              "pd",
              "rd",
              "sd",
              "tc"
            ]
          },
          "uniqueItems": true
        },
        "res": {
          "description": "What aspect ratios does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "1/1",
              "4/3",
              "5/4",
              "16/10",
              "16/9",
              "17/9",
              "21/9",
              "32/9"
            ]
          },
          "uniqueItems": true
        },
        "position": {
          "description": "What position is the ammo/health in the HUD (multiple customization options can be available)",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["center", "corners", "default"]
          },
          "uniqueItems": true
        },
        "lang": {
          "description": "What languages does the HUD support (if it has custom language files)",
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      }
    },
    "tags": {
      "description": "A list of words associated with the HUD for discovery. Be general. First tag is considered primary and used as a category. There is no list of valid tags, but they are subject to review for usefulness/'spamminess'.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repo": {
      "description": "The URL to the repository where the HUD is hosted",
      "type": "string"
    },
    "hash": {
      "description": "The hash of the latest commit in the repository",
      "type": "string"
    },
    "prerelease": {
      "description": "Whether the HUD is a prerelease",
      "type": "boolean"
    },
    "verified": {
      "description": "Whether the HUD has been verified by a member of the  team",
      "type": "boolean"
    },
    "parent": {
      "description": "The name of the HUD this HUD is based on",
      "type": "string"
    },
    "resources": {
      "description": "A list of resources associated with the HUD",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 15,
      "uniqueItems": true
    }
  }
}

=== 2fort-cremator/hud-db/hud-data/omp-hud.json
{
  "name": "OMP Hud",
  "author": "OMP",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "steam_group": "tf2hud",
    "album": "https://imgur.com/a/mCoYj"
  },
  "repo": "https://github.com/Hypnootize/OMP-Hud",
  "hash": "e051158f22ba1be5343eb9765451a037c8460589",
  "resources": [
    "omp-hud-banner"
  ]
}

=== 2fort-cremator/hud-db/hud-data/m0re-rockz.json
{
  "name": "m0re Rockz",
  "author": "Rockz",
  "social": {
    "album": "https://imgur.com/a/sebhnT6",
    "steam_profile": "http://steamcommunity.com/profiles/76561198071882999"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "16/9",
      "16/10"
    ]
  },
  "tags": [
    "minimal", 
    "competitive"
  ],
  "repo": "https://github.com/rrkkss/m0re-edit",
  "hash": "6cd4349c25f5afa696bf0411bf6e242f1d7a6ac8",
  "parent": "m0rehud",
  "resources": [
    "m0re-rockz-banner"
  ]
}

=== 2fort-cremator/hud-db/hud-data/voidhud.json
{
  "name": "voidHUD 2.0",
  "author": "staitc",
  "social": {
    "steam_group": "voidhud",
    "discord": "https://discord.com/invite/NtQ3FsT",
    "album": "https://imgur.com/a/VyZp5BV"
  },
  "repo": "https://github.com/cjrose/voidHUD",
  "hash": "8a2ffd04ade01b66952dfbe98e8273dd629a313a",
  "resources": [
    "voidhud-banner",
    "image00",
    "image01",
    "image02",
    "image03",
    "image04",
    "image05",
    "image06",
    "image07"
  ]
}

=== 2fort-cremator/hud-db/hud-data/darhud.json
{
  "name": "DarHUD",
  "author": "DarSitam",
  "contributors": [
    "DarSitam"
  ],
  "releaseDate": "2023-08-17",
  "flags": [
    "scoreboards",
    "minmode",
    "materials",
    "customization"
  ],
  "tags": [
    "modern"
  ],
  "repo": "https://github.com/DarSitam/DarHud",
  "hash": "83e8e85bc6faa0cb56bcb539c8b9bc8c4325ff60",
  "prerelease": false,
  "resources": [
    "darhud-logo"
  ],
  "social": {
    "steam_profile": "76561198148464161",
    "twitter": "DarSitam",
    "discord": "https://discord.gg/txn4CxyVmp",
    "youtube": "@DarSitam",
    "twitch": "DarSitam",
    "album": "https://imgur.com/a/pTE0V2X"
  },
  "traits": {
    "os": [
      "windows"
    ],
    "gamemode": [
      "tournament",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "sd"
    ],
    "res": [
      "4/3",
      "16/9"
    ],
    "position": [
      "center",
      "corners"
    ]
  }
}

=== 2fort-cremator/hud-db/hud-data/m0rehud.json
{
  "name": "m0rehud",
  "author": "Hypnotize",
  "social": {
    "steam_profile": "76561198058754493",
    "album": "https://imgur.com/a/sxOyM"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "crosshairs",
    "minmode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": [
      "4/3",
      "5/4",
      "16/9",
      "16/10"
    ],
    "position": [
      "center"
    ],
    "lang": [
      "en"
    ]
  },
  "repo": "https://github.com/Hypnootize/m0rehud",
  "hash": "996ade6b5abafe5f160cddef6d26057162516470",
  "resources": [
    "m0rehud-banner",
    "m0rehud-menu",
    "m0rehud-buff",
    "m0rehud-low",
    "m0rehud-minmode",
    "m0rehud-medic",
    "m0rehud-win",
    "m0rehud-scoreboard",
    "m0rehud-spectator"
  ]
}

=== 2fort-cremator/hud-db/hud-data/hudas-iscariote.json
{
  "name": "Hudas Iscariote",
  "author": "Hypnotize, Quartz & Sir Villeta",
  "social": {
    "steam_group": "KinevoNetwork",
    "album": "https://imgur.com/a/ag9He"
  },
  "repo": "https://github.com/Hypnootize/Hudas-Iscariote",
  "hash": "57819f4852eeba9043d03870b5d5acd94ad29d47",
  "resources": [
    "hudas-iscariote-banner"
  ]
}

=== 2fort-cremator/hud-db/hud-data/center-hud.json
{
  "name": "Center HUD",
  "author": "Eerorri",
  "releaseDate": "2023-12-23",
  "flags": [
    "fonts",
    "menus",
    "crosshairs",
    "minmode",
    "materials",
    "customization"
  ],
  "tags": ["vanilla", "default"],
  "repo": "https://github.com/Eerorri/center-hud",
  "hash": "9b7f760673449da5d582092acb2f9138b598dbcd",
  "prerelease": false,
  "resources": [
    "centerlogo",
    "center1",
    "center2",
    "center3",
    "center4",
    "center5",
    "https://youtu.be/a_38tTV4Xhc",
    "https://youtu.be/G39x7-gmCzU"
  ],
  "social": {
    "steam_profile": "76561199001745671",
    "twitter": "Eerorri_"
  },
  "traits": {
    "os": ["windows", "linux"],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": ["4/3", "16/9", "21/9"],
    "position": ["center"]
  }
}

=== 2fort-cremator/hud-db/hud-data/hud-fixes.json
{
  "name": "Community HUD Fixes",
  "author": "CriticalFlaw",
  "social": {
    "support": "https://github.com/sponsors/CriticalFlaw",
    "steam_profile": "76561198041892999",
    "twitter": "CriticalFlaw_",
    "discord": "hTdtK9vBhE",
    "youtube": "@CriticalFlaw"
  },
  "flags": [
    "crosshairs",
    "minmode",
    "materials",
    "customization"
  ],
  "traits": {
    "os": ["windows", "mac", "linux"],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr",
      "pd",
      "rd",
      "sd",
      "tc"
    ],
    "res": ["1/1", "4/3", "5/4", "16/10", "16/9", "17/9", "21/9", "32/9"],
    "position": ["default"],
    "lang": ["en"]
  },
  "tags": ["default"],
  "repo": "https://github.com/CriticalFlaw/TF2HUD.Fixes",
  "hash": "eabd28aa5d2436b45eb78f0bf61b33a96c018db3",
  "verified": true,
  "resources": [
    "banner"
  ]
}
