=== 2fort-cremator/hud-db/utils/hud-data.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "HUD Data",
  "description": "Data about a HUD",
  "type": "object",
  "required": ["name", "author", "repo", "hash", "resources"],
  "properties": {
    "name": {
      "description": "Display name of your HUD",
      "type": "string"
    },
    "author": {
      "description": "Display name of you, the active developer of the HUD (however, outdated HUD maintenance may not count as authoring in some cases)",
      "type": "string"
    },
    "contributors": {
      "description": "Display names of anyone you would like to credit for the creation/development of the HUD. Not to be used for general credits, but major and direct contributors",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "releaseDate": {
      "description": "Initial release date of the HUD",
      "type": "string"
    },
    "social": {
      "description": "Links to your social media profiles",
      "type": "object",
      "properties": {
        "support": {
          "description": "A link people can use to support you financially",
          "type": "string"
        },
        "issues": {
          "description": "An extra link where users can get help/report issues. If not present, will use GitHub Issues.",
          "type": "string"
        },
        "steam_profile": {
          "description": "Your SteamID64",
          "type": "string"
        },
        "steam_group": {
          "description": "Your Steam group",
          "type": "string"
        },
        "twitter": {
          "description": "Your Twitter handle",
          "type": "string"
        },
        "discord": {
          "description": "Your Discord invite code, not the full URL",
          "type": "string"
        },
        "album": {
          "description": "Link to some Imgur album or other to provide more images",
          "type": "string"
        }
      }
    },
    "flags": {
      "description": "A list of boolean flags whose presence indicates the existence of a feature of some kind",
      "type": "array",
      "items": {
        "type": "string",
        "enum": [
          "fonts",
          "menus",
          "scoreboards",
          "crosshairs",
          "minmode",
          "streamer-mode",
          "materials",
          "customization"
        ]
      },
      "uniqueItems": true
    },
    "traits": {
      "description": "Optional structured mapping of values",
      "type": "object",
      "properties": {
        "os": {
          "description": "What operating systems does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["windows", "mac", "linux"]
          },
          "uniqueItems": true
        },
        "gamemode": {
          "description": "What gamemodes does the HUD customize for",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "tournament",
              "comp",
              "arena",
              "ad",
              "ctf",
              "cp",
              "halloween",
              "koth",
              "mannpower",
              "mvm",
              "pass",
              "pl",
              "plr",
              "pd",
              "rd",
              "sd",
              "tc"
            ]
          },
          "uniqueItems": true
        },
        "res": {
          "description": "What aspect ratios does the HUD support",
          "type": "array",
          "items": {
            "type": "string",
            "enum": [
              "1/1",
              "4/3",
              "5/4",
              "16/10",
              "16/9",
              "17/9",
              "21/9",
              "32/9"
            ]
          },
          "uniqueItems": true
        },
        "position": {
          "description": "What position is the ammo/health in the HUD (multiple customization options can be available)",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["center", "corners", "default"]
          },
          "uniqueItems": true
        },
        "lang": {
          "description": "What languages does the HUD support (if it has custom language files)",
          "type": "array",
          "items": {
            "type": "string"
          },
          "uniqueItems": true
        }
      }
    },
    "tags": {
      "description": "A list of words associated with the HUD for discovery. Be general. First tag is considered primary and used as a category. There is no list of valid tags, but they are subject to review for usefulness/'spamminess'.",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "repo": {
      "description": "The URL to the repository where the HUD is hosted",
      "type": "string"
    },
    "hash": {
      "description": "The hash of the latest commit in the repository",
      "type": "string"
    },
    "prerelease": {
      "description": "Whether the HUD is a prerelease",
      "type": "boolean"
    },
    "verified": {
      "description": "Whether the HUD has been verified by a member of the  team",
      "type": "boolean"
    },
    "parent": {
      "description": "The name of the HUD this HUD is based on",
      "type": "string"
    },
    "resources": {
      "description": "A list of resources associated with the HUD",
      "type": "array",
      "items": {
        "type": "string"
      },
      "minItems": 1,
      "maxItems": 15,
      "uniqueItems": true
    }
  }
}

=== 2fort-cremator/hud-db/hud-data/supercomphud-omega.json
{
  "name": "SUPERCOMPHUD-OMEGA",
  "author": "kachowhero, lava",
  "releaseDate": "idk lol",
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "materials"
  ],
  "repo": "https://github.com/lavaOnoes/SUPERCOMPHUD-OMEGA",
  "hash": "3ae991e200d6d0ec71ef5cbe94ede6540b8a19e0",
  "prerelease": false,
  "resources": [
    "supercomphud-main",
    "https://www.youtube.com/watch?v=q8LgIzs_M2o"
  ],
  "social": {
    "steam_profile": "https://steamcommunity.com/id/alienblues/",
    "youtube": "@lavaOnoes"
  },
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "tournament",
      "comp",
      "arena",
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "mvm",
      "pass",
      "pl",
      "plr"
    ],
    "res": [
      "4/3",
      "16/10",
      "16/9"
    ]
  }
}

=== 2fort-cremator/hud-db/hud-data/broesel-hud.json
{
  "name": "Broesel Hud",
  "author": "Broesel",
  "contributors": [
    "Hypnotize"
  ],
  "social": {
    "steam_group": "broeselhud",
    "album": "https://imgur.com/a/YxG82"
  },
  "repo": "https://github.com/Hypnootize/Broesel-Hud",
  "hash": "ed6b267afcb93cedb114822d1268cfb0f0b148a3",
  "resources": [
    "broesel-hud-banner"
  ]
}

=== 2fort-cremator/hud-db/hud-data/delihud-neue.json
{
  "name": "deliHUD Neue",
  "author": "Deli",
  "social": {
    "steam_group": "deliHUD",
    "album": "https://imgur.com/a/ix8g52d"
  },
  "repo": "https://github.com/delegacz/deliHUDNeue",
  "hash": "37abc07a018e00abf9dd8989790523c22f08f858",
  "parent": "deli-hud",
  "resources": [
    "delihud-neue-banner"
  ]
}

=== 2fort-cremator/hud-db/hud-data/fragmenthud.json
{
  "name": "FRAGMENTHUD",
  "author": "leadscales",
  "contributors": [
    "fraxinus",
    "norsus",
    "eightyeight"
  ],
  "repo": "https://github.com/leadscales/fragmenthud",
  "hash": "2437c19c849c2c3468f6bf55779b787918fb26b7",
  "prerelease": true,
  "social": {
    "steam_profile": "76561199066986123",
    "discord": "yADdaAPvc4",
    "youtube": "@leadscales"
  },
  "flags": [
    "fonts",
    "menus",
    "scoreboards",
    "minmode",
    "materials",
    "customization"
  ],
  "tags": [
    "minimal",
    "duotone",
    "monochrome",
    "customizable",
    "modern"
  ],
  "traits": {
    "os": [
      "windows",
      "linux"
    ],
    "gamemode": [
      "ad",
      "ctf",
      "cp",
      "halloween",
      "koth",
      "mannpower",
      "pl",
      "plr",
      "sd"
    ],
    "res": [
      "4/3",
      "16/9",
      "16/10",
      "21/9",
      "32/9",
      "17/9"
    ],
    "position": [
      "center"
    ],
    "lang": [
      "en",
      "pt",
      "fr",
      "it",
      "pl",
      "ru",
      "es",
      "uk"
    ]
  },
  "resources": [
    "full",
    "mainmenu",
    "charinfo",
    "backpack",
    "loadout",
    "teammenu",
    "classmenu",
    "pl",
    "ad",
    "koth",
    "5cp",
    "ctf"
  ]
}

=== 2fort-cremator/hud-db/hud-data/peachhud.json
{
  "name": "PeachHUD",
  "author": "Peaches",
  "contributors": ["Hypnotize"],
  "social": {
    "steam_profile": "76561198406266064",
     "discord": "HyZRVtp",
     "album": "https://imgur.com/a/j6d9TjP"
  },
  "flags": ["fonts", "menus", "scoreboards", "crosshairs", "minmode", "streamer-mode", "materials", "customization"],
  "traits": {
    "os": ["windows", "mac", "linux"],
    "gamemode": ["tournament", "comp", "arena", "ad", "ctf", "cp", "halloween", "koth", "mannpower", "mvm", "pass", "pl", "plr", "pd", "rd", "sd", "tc"],
    "res": ["4/3", "5/4", "16/10", "16/9", "17/9", "21/9"],
    "position": ["center", "corners"]
  },
  "tags": ["minimal"],
  "repo": "https://github.com/PapaPeach/PeachHUD",
  "hash": "c4dd2c1fbc83cb52a531667caf71e4d2faa9e742",
  "resources": [
    "PeachHUD-banner",
    "ingame",
    "ingame-low",
    "scoreboard",
    "loadout",
    "darkmode"
  ]
}

=== 2fort-cremator/hud-db/hud-data/lackhud.json
{
    "name": "LackHUD",
    "author": "Arrhythmia",
    "contributors": [
      "techno"
    ],
    "social": {
      "album": "https://imgur.com/a/aYQhZd1"
    },
    "repo": "https://github.com/TechnoSL/LackHUD",
    "hash": "3e378660ad643dbf2c4a82f0f2eb87e69f21b1a8",
    "parent": "broesel-hud",
    "resources": [
      "lackhud-menu",
      "lackhud-gameplay"
    ]
  }

=== 2fort-cremator/hud-db/hud-data/broesel-old.json
{
  "name": "Broesel Old",
  "author": "Hypnotize, Broesel",
  "social": {
    "steam_group": "broeselhud",
    "album": "https://imgur.com/a/fG2xQ"
  },
  "repo": "https://github.com/Hypnootize/Broesel-Old",
  "hash": "ef087df34fffab7cfd62ac9ab2a8506b441f37d0",
  "parent": "broesel-hud",
  "resources": [
    "broesel-old-banner"
  ]
}

=== 2fort-cremator/hud-db/hud-data/tf2-recording-hud.json
{
  "name": "TF2 Recording HUD",
  "author": "Hypnotize",
  "social": {
    "steam_profile": "76561198058754493",
    "album": "https://imgur.com/a/PuONMo7"
  },
  "repo": "https://github.com/Hypnootize/TF2-Recording-HUD",
  "hash": "68b1912d8edbadfaa144f25b870bb1f45d0ec649",
  "resources": ["tf2-recording-hud-banner"]
}
